Bash-style comments for dependencies list, other fixes

diff --git a/scriptdata/functions b/scriptdata/functions
--- a/scriptdata/functions
+++ b/scriptdata/functions
@@ -1,8 +1,10 @@
 #!/usr/bin/env bash
 # This is NOT a script for execution, but for loading functions, so NOT need execution permission.
 # NOTE that you NOT need to `cd ..' because the `$0' is NOT this file, but the script file which will source this file.
-cd "$(dirname "$0")"
-export base="$(pwd)"
+
+# The script that use this file should have two lines on its top as follows:
+# cd "$(dirname "$0")"
+# export base="$(pwd)"
 
 function try { "$@" || sleep 0; }
 function v() {
@@ -60,4 +62,13 @@ function showfun() {
   printf "\e[32m"
   type -a $1
   printf "\e[97m"
+}
+function remove_bashcomments_emptylines(){
+  mkdir -p $(dirname $2)
+  cat $1 | sed -e '/^[[:blank:]]*#/d;s/#.*//' -e '/^[[:space:]]*$/d' > $2
+}
+function prevent_sudo_or_root(){
+  case $(whoami) in
+    root)echo -e "\e[31m[$0]: This script is NOT to be executed with sudo or as root. Aborting...\e[0m";exit 1;;
+  esac
 }
